[build]
  command = "CI=false npm run build"
  publish = "out"

[build.environment]
  NODE_ENV = "production"
  NEXT_PUBLIC_APP_URL = "https://strengthquest.netlify.app"
  NEXT_STATIC_EXPORT = "true" 