[build]
  command = """
    npm ci &&
    npx prisma generate &&
    npm run build &&
    mkdir -p .next/server/chunks &&
    cp prisma/production/prod.db .next/server/chunks/
  """
  publish = ".next"

[build.environment]
  NEXT_USE_NETLIFY_EDGE = "true"
  NEXT_PRIVATE_TARGET = "server"
  NODE_ENV = "production"

[[plugins]]
  package = "@netlify/plugin-nextjs" 