[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NEXT_USE_NETLIFY_EDGE = "true"
  NEXT_PRIVATE_TARGET = "server"
  NEXT_TELEMETRY_DISABLED = "1"
  NODE_ENV = "production"
  NEXT_PUBLIC_APP_URL = "https://strengthquest.netlify.app"

[[plugins]]
  package = "@netlify/plugin-nextjs" 