[build]
  command = """
    export NODE_ENV=production &&
    npm ci &&
    npx prisma generate &&
    npm run build -- --no-lint &&
    mkdir -p .next/server/chunks &&
    cp prisma/production/prod.db .next/server/chunks/
  """
  publish = ".next"

[build.environment]
  NEXT_USE_NETLIFY_EDGE = "true"
  NEXT_PRIVATE_TARGET = "server"
  NEXT_TELEMETRY_DISABLED = "1"
  SKIP_TYPE_CHECK = "1"

[[plugins]]
  package = "@netlify/plugin-nextjs" 